#stage 1
FROM node:alpine

WORKDIR '/app'

#COPY package.json .
COPY package*.json ./

RUN npm install
COPY . .
RUN npm run build

FROM nginx
EXPOSE 80
COPY --from=0 /app/build /usr/share/nginx/html

#CMD ["npm", "run", "start"]